# Use official NGINX Alpine image as base
FROM nginx:alpine

# Set timezone
RUN apk update && apk add --no-cache tzdata
RUN ln -sf /usr/share/zoneinfo/Asia/Makassar /etc/localtime

# Copy NGINX configuration
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

# Copy application files
COPY --chown=nginx public /var/www/html/public

# Set working directory
WORKDIR /var/www/html/public